#!/bin/bash -e
if ! id user > /dev/null 2>&1 ; then
		useradd -m user --shell /bin/bash
fi

USER_HOME=`echo ~user`

if [ ! -d $USER_HOME/oracle-plugin ]; then
        mkdir $USER_HOME/oracle-plugin
        chown user:sudo $USER_HOME/oracle-plugin/
fi
if [ ! -d $USER_HOME/data ]; then
        mkdir $USER_HOME/data
        chown user:sudo $USER_HOME/data/
fi
if [ ! -d $USER_HOME/data/oracle-plugin ]; then
        mkdir $USER_HOME/data/oracle-plugin
        chown user:sudo $USER_HOME/data/oracle-plugin
fi
if [ ! -L $USER_HOME/oracle-plugin/data ]; then
        ln -s $USER_HOME/data/oracle-plugin $USER_HOME/oracle-plugin/data
        chown user:sudo $USER_HOME/oracle-plugin/data
fi
