#!/bin/bash -e
if [ -x "/etc/init.d/oracle-plugin" ]; then
        if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
                invoke-rc.d oracle-plugin stop || true
        else
                /etc/init.d/oracle-plugin stop || true
        fi
fi
